TEST CASE
matthewblain/crosstowntrail-web pull request #6
Opened 2024-05-21 23:13 UTC by BobSiegel

2024-05-21 23:16 UTC, matthewblain requested changes
try again!

2024-05-21 23:16 UTC, matthewblain commented on cue-sheets/hike-north.md
> +Crosstown Trail Walk Cue Sheet, Sorthbound
You should fix the spellliiinng here!

2024-05-21 23:18 UTC, matthewblain reviewed
try now

2024-05-22 02:52 UTC, matthewblain approved these changes
Looks good. Would you like to share it with others first, they can see the diffs too?

2024-05-22 02:52 UTC, matthewblain commented on cue-sheets/hike-south.md
> +* Turn R at Crosstown Trail signpost to follow dirt path to R of white traffic barriers.
is this really a turn? or 'continue to R'?

2024-05-22 03:32 UTC, BobSiegel commented
No need to share it with others.  Upload with fervor!

On Tue, May 21, 2024, 7:52 PM matthewblain ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Looks good. Would you like to share it with others first, they can see the
> diffs too?
> ------------------------------
>
> In cue-sheets/hike-south.md
> <https://github.com/matthewblain/crosstowntrail-web/pull/6#discussion_r1609189629>
> :
>
> > @@ -176,8 +176,11 @@ Glen Park BART to Sunrise Point/Candlestick Point State Recreation Area
>  * Turn right on Blanken, opposite SFMTA T-Line Arleta stop. You are now in Little Hollywood neighborhood.
>  * After crossing Gillette, continue through tunnel on north sidewalk.
>  * Emerge from tunnel and bear left on Executive Park Blvd.
> -* At white gates, turn right to continue on Executive Park Blvd. Descend one block, and cross Harney Way to enter Candlestick Point State Recreation Area.
> -* Turn left on wide dirt path and walk past a parking lot that will soon be on your left.
> -* At fork, bear left on narrow dirt trail, and shortly thereafter, follow path on right side of white traffic barriers.
> -* Meander for about half a mile along dirt and asphalt trails closest to the shore of SF Bay.
> -* Section ends at paved roundabout at Sunrise Point. (**Restrooms**, picnic tables, fishing pier, campground by reservation.)
> +* At white gate, turn right to continue on Executive Park. Descend one block, and cross Harney to enter Candlestick Point State Recreation Area.
> +* Turn R at Crosstown Trail signpost.
> +* At next Crosstown Trail signpost located at beginning of colored concrete, turn L to follow dirt path going east with the bay on your right.
> +* At Y, bear R onto narrow path that proceeds toward white traffic barriers.
> +* Turn R at Crosstown Trail signpost to follow dirt path to R of white traffic barriers.
>
> is this really a turn? or 'continue to R'?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/matthewblain/crosstowntrail-web/pull/6#pullrequestreview-2070001900>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BIQYCAY3V2GURSVJA2YSZP3ZDQCAVAVCNFSM6AAAAABICQMSZKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANZQGAYDCOJQGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-22 03:35 UTC, merged